//
//  UIAnimationContext.swift
//  UIAnimationToolbox
//
//  Created by WeZZard on 1/31/16.
//
//

import UIKit

public protocol UIAnimationContext: NSObjectProtocol {
    /// Use this function to generate a custom animation in UIKit 
    /// animation block.
    ///
    /// - Notes: Both UIView custom animatable properties and preset
    /// animatable properties do not use this function to generate 
    /// animation.
    func createAnimation() -> CAAnimation
    
    /// Use this function to configure the animation generated by
    /// `createAnimation()` with the parameters derived from UIKit 
    /// animation block.
    ///
    /// - Notes: UIView custom animatable properties also use this 
    /// function to configure the animation with the parameters derived 
    /// from UIKit animation API.
    func configureAnimation(_ animation: CAAnimation) -> Bool
    
    /// Tells the type of animations generated by `createAnimation()`.
    ///
    /// Returns `CABasicAnimation` in block of regular UIKit animation,
    /// `CASpringAnimation` in block of spring UIKit animation. Doesn't
    /// support keyframe animation currently.
    var animationType: CAAnimation.Type { get }
    
    /// Returns the duration setting of the UIKit animation block
    var duration: TimeInterval { get }
    
    /// Returns the delay setting of the UIKit animation block
    var delay: TimeInterval { get }
}
